name: Deploy Frontend

on:
  push:
    paths:
      - 'hexacloud_fe/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.87.183.72 >> ~/.ssh/known_hosts

      - name: Deploy Frontend to VPS
        run: |
          ssh thiennlse172858@34.87.183.72 << 'EOF'
            cd ~/hexacloud_fe
            git pull origin main
            npm install
            npm run build
            pm2 restart hexafe
          EOF
